apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: github-token-generator
  name: github-token-generator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-token-generator
  template:
    metadata:
      labels:
        app: github-token-generator
    spec:
      containers:
        - image: ghcr.io/mtsmfm/devfiles/ruby:3.0-node-16
          imagePullPolicy: Always
          name: ruby
          volumeMounts:
            - mountPath: /workspace
              subPath: workspace
              name: workspace
            - mountPath: /home/user/.vscode-server/extensions
              subPath: extensions
              name: workspace
      securityContext:
        runAsUser: 1000
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: workspace
